//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backlog
    {
        public int BacklogID { get; set; }
        public string Backlog_Description { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> OrderLineID { get; set; }
        public Nullable<decimal> BacklogQty { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Order_Line Order_Line { get; set; }
    }
}
