//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation_Procedure
    {
        public int Consultation_ProcedureID { get; set; }
        public int Consultation_ID { get; set; }
        public int Procedure_ID { get; set; }
        public string ProcedureNotes { get; set; }
        public Nullable<int> Appointment_ID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Consultation Consultation { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
