//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation_Ailment
    {
        public int Consultation_ID { get; set; }
        public int Ailment_ID { get; set; }
        public string Notes { get; set; }
    
        public virtual Ailment Ailment { get; set; }
        public virtual Consultation Consultation { get; set; }
    }
}
