//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Aid_Claim
    {
        public int Medical_Aid_Claim_ID { get; set; }
        public decimal Claim_Amount { get; set; }
        public System.DateTime Claim_Date { get; set; }
        public string Claim_Description { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public int Consultation_ID { get; set; }
        public string ClaimStatus { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
