//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileApp
    {
        public int MobileAppID { get; set; }
        public int AppointmentID { get; set; }
        public string AppDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string PatientName { get; set; }
        public string PatientSurname { get; set; }
        public string AppDescr { get; set; }
        public string StartDateTime { get; set; }
        public string EndDateTime { get; set; }
        public string FullName { get; set; }
    }
}
