//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Payment
    {
        public int Order_Payment_ID { get; set; }
        public System.DateTime Order_Payment_Date { get; set; }
        public decimal Order_Payment_Amount { get; set; }
        public int OrderID { get; set; }
        public int Payment_Type_ID { get; set; }
        public string ReceiptNumber { get; set; }
        public string TransactionNumber { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
    }
}
