//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Medical_Aid_Claim = new HashSet<Medical_Aid_Claim>();
        }
    
        public int Payment_ID { get; set; }
        public decimal Payment_Amount { get; set; }
        public int Consultation_ID { get; set; }
        public int Payment_Type_ID { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Aid_Claim> Medical_Aid_Claim { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
    }
}
