//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Line
    {
        public int PrescriptionLineID { get; set; }
        public Nullable<System.DateTime> Perscription_Date { get; set; }
        public string Intake { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public int Consultation_ID { get; set; }
        public Nullable<int> Medication_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Medication Medication { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
