//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Procedure
    {
        public int ProductProcedureID { get; set; }
        public int Procedure_ID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Procedure Procedure { get; set; }
        public virtual Product Product { get; set; }
    }
}
