//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconcilliation
    {
        public int ReconID { get; set; }
        public decimal RealisedQty { get; set; }
        public string ReasonDescription { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
