//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_take_Line
    {
        public int Stock_Take_Line_ID { get; set; }
        public int ProductID { get; set; }
        public int StockTake_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Stock_Take Stock_Take { get; set; }
    }
}
