//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrSavvy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xray
    {
        public int XrayID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Consultation_ID { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
